#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-zip
Version  : 1.0.0
Release  : 3
URL      : https://cran.r-project.org/src/contrib/zip_1.0.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/zip_1.0.0.tar.gz
Summary  : Cross-Platform 'zip' Compression
Group    : Development/Tools
License  : CC0-1.0
Requires: R-zip-lib
BuildRequires : clr-R-helpers

%description
for the 'zip' function, that does not require any additional
    external tools on any platform.

%package lib
Summary: lib components for the R-zip package.
Group: Libraries

%description lib
lib components for the R-zip package.


%prep
%setup -q -c -n zip

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1527658908

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1527658908
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library zip
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library zip
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library zip
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library zip|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/zip/DESCRIPTION
/usr/lib64/R/library/zip/INDEX
/usr/lib64/R/library/zip/Meta/Rd.rds
/usr/lib64/R/library/zip/Meta/features.rds
/usr/lib64/R/library/zip/Meta/hsearch.rds
/usr/lib64/R/library/zip/Meta/links.rds
/usr/lib64/R/library/zip/Meta/nsInfo.rds
/usr/lib64/R/library/zip/Meta/package.rds
/usr/lib64/R/library/zip/NAMESPACE
/usr/lib64/R/library/zip/NEWS.md
/usr/lib64/R/library/zip/R/zip
/usr/lib64/R/library/zip/R/zip.rdb
/usr/lib64/R/library/zip/R/zip.rdx
/usr/lib64/R/library/zip/help/AnIndex
/usr/lib64/R/library/zip/help/aliases.rds
/usr/lib64/R/library/zip/help/paths.rds
/usr/lib64/R/library/zip/help/zip.rdb
/usr/lib64/R/library/zip/help/zip.rdx
/usr/lib64/R/library/zip/html/00Index.html
/usr/lib64/R/library/zip/html/R.css
/usr/lib64/R/library/zip/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/zip/libs/zip.so
/usr/lib64/R/library/zip/libs/zip.so.avx2
/usr/lib64/R/library/zip/libs/zip.so.avx512
